// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/secret-server/client-api/models"
)

// SecretsServiceGetSecretExtendedSearchDetailsReader is a Reader for the SecretsServiceGetSecretExtendedSearchDetails structure.
type SecretsServiceGetSecretExtendedSearchDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecretsServiceGetSecretExtendedSearchDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecretsServiceGetSecretExtendedSearchDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSecretsServiceGetSecretExtendedSearchDetailsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSecretsServiceGetSecretExtendedSearchDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSecretsServiceGetSecretExtendedSearchDetailsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/secrets/extended-search-details] SecretsService_GetSecretExtendedSearchDetails", response, response.Code())
	}
}

// NewSecretsServiceGetSecretExtendedSearchDetailsOK creates a SecretsServiceGetSecretExtendedSearchDetailsOK with default headers values
func NewSecretsServiceGetSecretExtendedSearchDetailsOK() *SecretsServiceGetSecretExtendedSearchDetailsOK {
	return &SecretsServiceGetSecretExtendedSearchDetailsOK{}
}

/*
SecretsServiceGetSecretExtendedSearchDetailsOK describes a response with status code 200, with default header values.

Secret search extended details
*/
type SecretsServiceGetSecretExtendedSearchDetailsOK struct {
	Payload []*models.SecretSearchExtendedSummary
}

// IsSuccess returns true when this secrets service get secret extended search details o k response has a 2xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this secrets service get secret extended search details o k response has a 3xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get secret extended search details o k response has a 4xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get secret extended search details o k response has a 5xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get secret extended search details o k response a status code equal to that given
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the secrets service get secret extended search details o k response
func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) Code() int {
	return 200
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) String() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) GetPayload() []*models.SecretSearchExtendedSummary {
	return o.Payload
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetSecretExtendedSearchDetailsBadRequest creates a SecretsServiceGetSecretExtendedSearchDetailsBadRequest with default headers values
func NewSecretsServiceGetSecretExtendedSearchDetailsBadRequest() *SecretsServiceGetSecretExtendedSearchDetailsBadRequest {
	return &SecretsServiceGetSecretExtendedSearchDetailsBadRequest{}
}

/*
SecretsServiceGetSecretExtendedSearchDetailsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SecretsServiceGetSecretExtendedSearchDetailsBadRequest struct {
	Payload *models.BadRequestResponse
}

// IsSuccess returns true when this secrets service get secret extended search details bad request response has a 2xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get secret extended search details bad request response has a 3xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get secret extended search details bad request response has a 4xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get secret extended search details bad request response has a 5xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get secret extended search details bad request response a status code equal to that given
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the secrets service get secret extended search details bad request response
func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) Code() int {
	return 400
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) String() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) GetPayload() *models.BadRequestResponse {
	return o.Payload
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetSecretExtendedSearchDetailsForbidden creates a SecretsServiceGetSecretExtendedSearchDetailsForbidden with default headers values
func NewSecretsServiceGetSecretExtendedSearchDetailsForbidden() *SecretsServiceGetSecretExtendedSearchDetailsForbidden {
	return &SecretsServiceGetSecretExtendedSearchDetailsForbidden{}
}

/*
SecretsServiceGetSecretExtendedSearchDetailsForbidden describes a response with status code 403, with default header values.

Authentication failed
*/
type SecretsServiceGetSecretExtendedSearchDetailsForbidden struct {
	Payload *models.AuthenticationFailedResponse
}

// IsSuccess returns true when this secrets service get secret extended search details forbidden response has a 2xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get secret extended search details forbidden response has a 3xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get secret extended search details forbidden response has a 4xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get secret extended search details forbidden response has a 5xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get secret extended search details forbidden response a status code equal to that given
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the secrets service get secret extended search details forbidden response
func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) Code() int {
	return 403
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) Error() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) String() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) GetPayload() *models.AuthenticationFailedResponse {
	return o.Payload
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationFailedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetSecretExtendedSearchDetailsInternalServerError creates a SecretsServiceGetSecretExtendedSearchDetailsInternalServerError with default headers values
func NewSecretsServiceGetSecretExtendedSearchDetailsInternalServerError() *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError {
	return &SecretsServiceGetSecretExtendedSearchDetailsInternalServerError{}
}

/*
SecretsServiceGetSecretExtendedSearchDetailsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type SecretsServiceGetSecretExtendedSearchDetailsInternalServerError struct {
	Payload *models.InternalServerErrorResponse
}

// IsSuccess returns true when this secrets service get secret extended search details internal server error response has a 2xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get secret extended search details internal server error response has a 3xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get secret extended search details internal server error response has a 4xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get secret extended search details internal server error response has a 5xx status code
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this secrets service get secret extended search details internal server error response a status code equal to that given
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the secrets service get secret extended search details internal server error response
func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) Code() int {
	return 500
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) String() string {
	return fmt.Sprintf("[POST /api/v1/secrets/extended-search-details][%d] secretsServiceGetSecretExtendedSearchDetailsInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) GetPayload() *models.InternalServerErrorResponse {
	return o.Payload
}

func (o *SecretsServiceGetSecretExtendedSearchDetailsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
