// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/secret-server/client-api/models"
)

// SecretsServiceGetFieldReader is a Reader for the SecretsServiceGetField structure.
type SecretsServiceGetFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecretsServiceGetFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecretsServiceGetFieldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSecretsServiceGetFieldBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSecretsServiceGetFieldForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSecretsServiceGetFieldInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/secrets/{id}/fields/{slug}] SecretsService_GetField", response, response.Code())
	}
}

// NewSecretsServiceGetFieldOK creates a SecretsServiceGetFieldOK with default headers values
func NewSecretsServiceGetFieldOK() *SecretsServiceGetFieldOK {
	return &SecretsServiceGetFieldOK{}
}

/*
SecretsServiceGetFieldOK describes a response with status code 200, with default header values.

Secret field value. If the field is a file attachment, the content type will be `application/octet-stream` and the response body will be the file contents.
*/
type SecretsServiceGetFieldOK struct {
	Payload string
}

// IsSuccess returns true when this secrets service get field o k response has a 2xx status code
func (o *SecretsServiceGetFieldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this secrets service get field o k response has a 3xx status code
func (o *SecretsServiceGetFieldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get field o k response has a 4xx status code
func (o *SecretsServiceGetFieldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get field o k response has a 5xx status code
func (o *SecretsServiceGetFieldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get field o k response a status code equal to that given
func (o *SecretsServiceGetFieldOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the secrets service get field o k response
func (o *SecretsServiceGetFieldOK) Code() int {
	return 200
}

func (o *SecretsServiceGetFieldOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetFieldOK) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetFieldOK) GetPayload() string {
	return o.Payload
}

func (o *SecretsServiceGetFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetFieldBadRequest creates a SecretsServiceGetFieldBadRequest with default headers values
func NewSecretsServiceGetFieldBadRequest() *SecretsServiceGetFieldBadRequest {
	return &SecretsServiceGetFieldBadRequest{}
}

/*
SecretsServiceGetFieldBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SecretsServiceGetFieldBadRequest struct {
	Payload *models.BadRequestResponse
}

// IsSuccess returns true when this secrets service get field bad request response has a 2xx status code
func (o *SecretsServiceGetFieldBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get field bad request response has a 3xx status code
func (o *SecretsServiceGetFieldBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get field bad request response has a 4xx status code
func (o *SecretsServiceGetFieldBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get field bad request response has a 5xx status code
func (o *SecretsServiceGetFieldBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get field bad request response a status code equal to that given
func (o *SecretsServiceGetFieldBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the secrets service get field bad request response
func (o *SecretsServiceGetFieldBadRequest) Code() int {
	return 400
}

func (o *SecretsServiceGetFieldBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetFieldBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetFieldBadRequest) GetPayload() *models.BadRequestResponse {
	return o.Payload
}

func (o *SecretsServiceGetFieldBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetFieldForbidden creates a SecretsServiceGetFieldForbidden with default headers values
func NewSecretsServiceGetFieldForbidden() *SecretsServiceGetFieldForbidden {
	return &SecretsServiceGetFieldForbidden{}
}

/*
SecretsServiceGetFieldForbidden describes a response with status code 403, with default header values.

Authentication failed
*/
type SecretsServiceGetFieldForbidden struct {
	Payload *models.AuthenticationFailedResponse
}

// IsSuccess returns true when this secrets service get field forbidden response has a 2xx status code
func (o *SecretsServiceGetFieldForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get field forbidden response has a 3xx status code
func (o *SecretsServiceGetFieldForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get field forbidden response has a 4xx status code
func (o *SecretsServiceGetFieldForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get field forbidden response has a 5xx status code
func (o *SecretsServiceGetFieldForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get field forbidden response a status code equal to that given
func (o *SecretsServiceGetFieldForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the secrets service get field forbidden response
func (o *SecretsServiceGetFieldForbidden) Code() int {
	return 403
}

func (o *SecretsServiceGetFieldForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetFieldForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetFieldForbidden) GetPayload() *models.AuthenticationFailedResponse {
	return o.Payload
}

func (o *SecretsServiceGetFieldForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationFailedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetFieldInternalServerError creates a SecretsServiceGetFieldInternalServerError with default headers values
func NewSecretsServiceGetFieldInternalServerError() *SecretsServiceGetFieldInternalServerError {
	return &SecretsServiceGetFieldInternalServerError{}
}

/*
SecretsServiceGetFieldInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type SecretsServiceGetFieldInternalServerError struct {
	Payload *models.InternalServerErrorResponse
}

// IsSuccess returns true when this secrets service get field internal server error response has a 2xx status code
func (o *SecretsServiceGetFieldInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get field internal server error response has a 3xx status code
func (o *SecretsServiceGetFieldInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get field internal server error response has a 4xx status code
func (o *SecretsServiceGetFieldInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get field internal server error response has a 5xx status code
func (o *SecretsServiceGetFieldInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this secrets service get field internal server error response a status code equal to that given
func (o *SecretsServiceGetFieldInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the secrets service get field internal server error response
func (o *SecretsServiceGetFieldInternalServerError) Code() int {
	return 500
}

func (o *SecretsServiceGetFieldInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetFieldInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}][%d] secretsServiceGetFieldInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetFieldInternalServerError) GetPayload() *models.InternalServerErrorResponse {
	return o.Payload
}

func (o *SecretsServiceGetFieldInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
