// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSecretsServiceGetFieldParams creates a new SecretsServiceGetFieldParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecretsServiceGetFieldParams() *SecretsServiceGetFieldParams {
	return &SecretsServiceGetFieldParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsServiceGetFieldParamsWithTimeout creates a new SecretsServiceGetFieldParams object
// with the ability to set a timeout on a request.
func NewSecretsServiceGetFieldParamsWithTimeout(timeout time.Duration) *SecretsServiceGetFieldParams {
	return &SecretsServiceGetFieldParams{
		timeout: timeout,
	}
}

// NewSecretsServiceGetFieldParamsWithContext creates a new SecretsServiceGetFieldParams object
// with the ability to set a context for a request.
func NewSecretsServiceGetFieldParamsWithContext(ctx context.Context) *SecretsServiceGetFieldParams {
	return &SecretsServiceGetFieldParams{
		Context: ctx,
	}
}

// NewSecretsServiceGetFieldParamsWithHTTPClient creates a new SecretsServiceGetFieldParams object
// with the ability to set a custom HTTPClient for a request.
func NewSecretsServiceGetFieldParamsWithHTTPClient(client *http.Client) *SecretsServiceGetFieldParams {
	return &SecretsServiceGetFieldParams{
		HTTPClient: client,
	}
}

/*
SecretsServiceGetFieldParams contains all the parameters to send to the API endpoint

	for the secrets service get field operation.

	Typically these are written to a http.Request.
*/
type SecretsServiceGetFieldParams struct {

	/* AutoCheckIn.

	   Automatically check in a secret after finding or updating.
	*/
	AutoCheckIn *bool

	/* AutoCheckout.

	   Automatically check out secret before finding or updating.
	*/
	AutoCheckout *bool

	/* AutoComment.

	   Leave a comment when checking in or out.
	*/
	AutoComment *string

	/* ForceCheckIn.

	   If secret is checked out, then force a check in.
	*/
	ForceCheckIn *bool

	/* ID.

	   Secret ID

	   Format: int32
	*/
	ID int32

	/* IncludeInactive.

	   Whether to include inactive secrets in the results
	*/
	IncludeInactive *bool

	/* NoAutoCheckout.

	   Don't check out the secret if needed
	*/
	NoAutoCheckout *bool

	/* SecretPath.

	   A full path including folder and secret name can be passed as a query string parameter when the secret ID is set to 0.  This will lookup the secret ID by path.
	*/
	SecretPath *string

	/* Slug.

	   Secret field name
	*/
	Slug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the secrets service get field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceGetFieldParams) WithDefaults() *SecretsServiceGetFieldParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the secrets service get field params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceGetFieldParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithTimeout(timeout time.Duration) *SecretsServiceGetFieldParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithContext(ctx context.Context) *SecretsServiceGetFieldParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithHTTPClient(client *http.Client) *SecretsServiceGetFieldParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAutoCheckIn adds the autoCheckIn to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithAutoCheckIn(autoCheckIn *bool) *SecretsServiceGetFieldParams {
	o.SetAutoCheckIn(autoCheckIn)
	return o
}

// SetAutoCheckIn adds the autoCheckIn to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetAutoCheckIn(autoCheckIn *bool) {
	o.AutoCheckIn = autoCheckIn
}

// WithAutoCheckout adds the autoCheckout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithAutoCheckout(autoCheckout *bool) *SecretsServiceGetFieldParams {
	o.SetAutoCheckout(autoCheckout)
	return o
}

// SetAutoCheckout adds the autoCheckout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetAutoCheckout(autoCheckout *bool) {
	o.AutoCheckout = autoCheckout
}

// WithAutoComment adds the autoComment to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithAutoComment(autoComment *string) *SecretsServiceGetFieldParams {
	o.SetAutoComment(autoComment)
	return o
}

// SetAutoComment adds the autoComment to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetAutoComment(autoComment *string) {
	o.AutoComment = autoComment
}

// WithForceCheckIn adds the forceCheckIn to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithForceCheckIn(forceCheckIn *bool) *SecretsServiceGetFieldParams {
	o.SetForceCheckIn(forceCheckIn)
	return o
}

// SetForceCheckIn adds the forceCheckIn to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetForceCheckIn(forceCheckIn *bool) {
	o.ForceCheckIn = forceCheckIn
}

// WithID adds the id to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithID(id int32) *SecretsServiceGetFieldParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetID(id int32) {
	o.ID = id
}

// WithIncludeInactive adds the includeInactive to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithIncludeInactive(includeInactive *bool) *SecretsServiceGetFieldParams {
	o.SetIncludeInactive(includeInactive)
	return o
}

// SetIncludeInactive adds the includeInactive to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetIncludeInactive(includeInactive *bool) {
	o.IncludeInactive = includeInactive
}

// WithNoAutoCheckout adds the noAutoCheckout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithNoAutoCheckout(noAutoCheckout *bool) *SecretsServiceGetFieldParams {
	o.SetNoAutoCheckout(noAutoCheckout)
	return o
}

// SetNoAutoCheckout adds the noAutoCheckout to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetNoAutoCheckout(noAutoCheckout *bool) {
	o.NoAutoCheckout = noAutoCheckout
}

// WithSecretPath adds the secretPath to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithSecretPath(secretPath *string) *SecretsServiceGetFieldParams {
	o.SetSecretPath(secretPath)
	return o
}

// SetSecretPath adds the secretPath to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetSecretPath(secretPath *string) {
	o.SecretPath = secretPath
}

// WithSlug adds the slug to the secrets service get field params
func (o *SecretsServiceGetFieldParams) WithSlug(slug string) *SecretsServiceGetFieldParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the secrets service get field params
func (o *SecretsServiceGetFieldParams) SetSlug(slug string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsServiceGetFieldParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AutoCheckIn != nil {

		// query param autoCheckIn
		var qrAutoCheckIn bool

		if o.AutoCheckIn != nil {
			qrAutoCheckIn = *o.AutoCheckIn
		}
		qAutoCheckIn := swag.FormatBool(qrAutoCheckIn)
		if qAutoCheckIn != "" {

			if err := r.SetQueryParam("autoCheckIn", qAutoCheckIn); err != nil {
				return err
			}
		}
	}

	if o.AutoCheckout != nil {

		// query param autoCheckout
		var qrAutoCheckout bool

		if o.AutoCheckout != nil {
			qrAutoCheckout = *o.AutoCheckout
		}
		qAutoCheckout := swag.FormatBool(qrAutoCheckout)
		if qAutoCheckout != "" {

			if err := r.SetQueryParam("autoCheckout", qAutoCheckout); err != nil {
				return err
			}
		}
	}

	if o.AutoComment != nil {

		// query param autoComment
		var qrAutoComment string

		if o.AutoComment != nil {
			qrAutoComment = *o.AutoComment
		}
		qAutoComment := qrAutoComment
		if qAutoComment != "" {

			if err := r.SetQueryParam("autoComment", qAutoComment); err != nil {
				return err
			}
		}
	}

	if o.ForceCheckIn != nil {

		// query param forceCheckIn
		var qrForceCheckIn bool

		if o.ForceCheckIn != nil {
			qrForceCheckIn = *o.ForceCheckIn
		}
		qForceCheckIn := swag.FormatBool(qrForceCheckIn)
		if qForceCheckIn != "" {

			if err := r.SetQueryParam("forceCheckIn", qForceCheckIn); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.IncludeInactive != nil {

		// query param includeInactive
		var qrIncludeInactive bool

		if o.IncludeInactive != nil {
			qrIncludeInactive = *o.IncludeInactive
		}
		qIncludeInactive := swag.FormatBool(qrIncludeInactive)
		if qIncludeInactive != "" {

			if err := r.SetQueryParam("includeInactive", qIncludeInactive); err != nil {
				return err
			}
		}
	}

	if o.NoAutoCheckout != nil {

		// query param noAutoCheckout
		var qrNoAutoCheckout bool

		if o.NoAutoCheckout != nil {
			qrNoAutoCheckout = *o.NoAutoCheckout
		}
		qNoAutoCheckout := swag.FormatBool(qrNoAutoCheckout)
		if qNoAutoCheckout != "" {

			if err := r.SetQueryParam("noAutoCheckout", qNoAutoCheckout); err != nil {
				return err
			}
		}
	}

	if o.SecretPath != nil {

		// query param secretPath
		var qrSecretPath string

		if o.SecretPath != nil {
			qrSecretPath = *o.SecretPath
		}
		qSecretPath := qrSecretPath
		if qSecretPath != "" {

			if err := r.SetQueryParam("secretPath", qSecretPath); err != nil {
				return err
			}
		}
	}

	// path param slug
	if err := r.SetPathParam("slug", o.Slug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
