// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/secret-server/client-api/models"
)

// SecretsServiceGetListFieldListDefinitionsReader is a Reader for the SecretsServiceGetListFieldListDefinitions structure.
type SecretsServiceGetListFieldListDefinitionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecretsServiceGetListFieldListDefinitionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecretsServiceGetListFieldListDefinitionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSecretsServiceGetListFieldListDefinitionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSecretsServiceGetListFieldListDefinitionsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSecretsServiceGetListFieldListDefinitionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails] SecretsService_GetListFieldListDefinitions", response, response.Code())
	}
}

// NewSecretsServiceGetListFieldListDefinitionsOK creates a SecretsServiceGetListFieldListDefinitionsOK with default headers values
func NewSecretsServiceGetListFieldListDefinitionsOK() *SecretsServiceGetListFieldListDefinitionsOK {
	return &SecretsServiceGetListFieldListDefinitionsOK{}
}

/*
SecretsServiceGetListFieldListDefinitionsOK describes a response with status code 200, with default header values.

Combined summary of all lists assigned to the secret field.
*/
type SecretsServiceGetListFieldListDefinitionsOK struct {
	Payload *models.PagingOfCategorizedListSummary
}

// IsSuccess returns true when this secrets service get list field list definitions o k response has a 2xx status code
func (o *SecretsServiceGetListFieldListDefinitionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this secrets service get list field list definitions o k response has a 3xx status code
func (o *SecretsServiceGetListFieldListDefinitionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field list definitions o k response has a 4xx status code
func (o *SecretsServiceGetListFieldListDefinitionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get list field list definitions o k response has a 5xx status code
func (o *SecretsServiceGetListFieldListDefinitionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field list definitions o k response a status code equal to that given
func (o *SecretsServiceGetListFieldListDefinitionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the secrets service get list field list definitions o k response
func (o *SecretsServiceGetListFieldListDefinitionsOK) Code() int {
	return 200
}

func (o *SecretsServiceGetListFieldListDefinitionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsOK) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsOK) GetPayload() *models.PagingOfCategorizedListSummary {
	return o.Payload
}

func (o *SecretsServiceGetListFieldListDefinitionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagingOfCategorizedListSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldListDefinitionsBadRequest creates a SecretsServiceGetListFieldListDefinitionsBadRequest with default headers values
func NewSecretsServiceGetListFieldListDefinitionsBadRequest() *SecretsServiceGetListFieldListDefinitionsBadRequest {
	return &SecretsServiceGetListFieldListDefinitionsBadRequest{}
}

/*
SecretsServiceGetListFieldListDefinitionsBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SecretsServiceGetListFieldListDefinitionsBadRequest struct {
	Payload *models.BadRequestResponse
}

// IsSuccess returns true when this secrets service get list field list definitions bad request response has a 2xx status code
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field list definitions bad request response has a 3xx status code
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field list definitions bad request response has a 4xx status code
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get list field list definitions bad request response has a 5xx status code
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field list definitions bad request response a status code equal to that given
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the secrets service get list field list definitions bad request response
func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) Code() int {
	return 400
}

func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) GetPayload() *models.BadRequestResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldListDefinitionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldListDefinitionsForbidden creates a SecretsServiceGetListFieldListDefinitionsForbidden with default headers values
func NewSecretsServiceGetListFieldListDefinitionsForbidden() *SecretsServiceGetListFieldListDefinitionsForbidden {
	return &SecretsServiceGetListFieldListDefinitionsForbidden{}
}

/*
SecretsServiceGetListFieldListDefinitionsForbidden describes a response with status code 403, with default header values.

Authentication failed
*/
type SecretsServiceGetListFieldListDefinitionsForbidden struct {
	Payload *models.AuthenticationFailedResponse
}

// IsSuccess returns true when this secrets service get list field list definitions forbidden response has a 2xx status code
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field list definitions forbidden response has a 3xx status code
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field list definitions forbidden response has a 4xx status code
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get list field list definitions forbidden response has a 5xx status code
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field list definitions forbidden response a status code equal to that given
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the secrets service get list field list definitions forbidden response
func (o *SecretsServiceGetListFieldListDefinitionsForbidden) Code() int {
	return 403
}

func (o *SecretsServiceGetListFieldListDefinitionsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsForbidden) GetPayload() *models.AuthenticationFailedResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldListDefinitionsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationFailedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldListDefinitionsInternalServerError creates a SecretsServiceGetListFieldListDefinitionsInternalServerError with default headers values
func NewSecretsServiceGetListFieldListDefinitionsInternalServerError() *SecretsServiceGetListFieldListDefinitionsInternalServerError {
	return &SecretsServiceGetListFieldListDefinitionsInternalServerError{}
}

/*
SecretsServiceGetListFieldListDefinitionsInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type SecretsServiceGetListFieldListDefinitionsInternalServerError struct {
	Payload *models.InternalServerErrorResponse
}

// IsSuccess returns true when this secrets service get list field list definitions internal server error response has a 2xx status code
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field list definitions internal server error response has a 3xx status code
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field list definitions internal server error response has a 4xx status code
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get list field list definitions internal server error response has a 5xx status code
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this secrets service get list field list definitions internal server error response a status code equal to that given
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the secrets service get list field list definitions internal server error response
func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) Code() int {
	return 500
}

func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/listdetails][%d] secretsServiceGetListFieldListDefinitionsInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) GetPayload() *models.InternalServerErrorResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldListDefinitionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
