// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/secret-server/client-api/models"
)

// SecretsServiceGetListFieldReader is a Reader for the SecretsServiceGetListField structure.
type SecretsServiceGetListFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecretsServiceGetListFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecretsServiceGetListFieldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSecretsServiceGetListFieldBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSecretsServiceGetListFieldForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSecretsServiceGetListFieldInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/secrets/{id}/fields/{slug}/list] SecretsService_GetListField", response, response.Code())
	}
}

// NewSecretsServiceGetListFieldOK creates a SecretsServiceGetListFieldOK with default headers values
func NewSecretsServiceGetListFieldOK() *SecretsServiceGetListFieldOK {
	return &SecretsServiceGetListFieldOK{}
}

/*
SecretsServiceGetListFieldOK describes a response with status code 200, with default header values.

Combined contents of all lists assigned to the secret field.
*/
type SecretsServiceGetListFieldOK struct {
	Payload *models.CategorizedListItemValueResult
}

// IsSuccess returns true when this secrets service get list field o k response has a 2xx status code
func (o *SecretsServiceGetListFieldOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this secrets service get list field o k response has a 3xx status code
func (o *SecretsServiceGetListFieldOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field o k response has a 4xx status code
func (o *SecretsServiceGetListFieldOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get list field o k response has a 5xx status code
func (o *SecretsServiceGetListFieldOK) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field o k response a status code equal to that given
func (o *SecretsServiceGetListFieldOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the secrets service get list field o k response
func (o *SecretsServiceGetListFieldOK) Code() int {
	return 200
}

func (o *SecretsServiceGetListFieldOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetListFieldOK) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldOK  %+v", 200, o.Payload)
}

func (o *SecretsServiceGetListFieldOK) GetPayload() *models.CategorizedListItemValueResult {
	return o.Payload
}

func (o *SecretsServiceGetListFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CategorizedListItemValueResult)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldBadRequest creates a SecretsServiceGetListFieldBadRequest with default headers values
func NewSecretsServiceGetListFieldBadRequest() *SecretsServiceGetListFieldBadRequest {
	return &SecretsServiceGetListFieldBadRequest{}
}

/*
SecretsServiceGetListFieldBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type SecretsServiceGetListFieldBadRequest struct {
	Payload *models.BadRequestResponse
}

// IsSuccess returns true when this secrets service get list field bad request response has a 2xx status code
func (o *SecretsServiceGetListFieldBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field bad request response has a 3xx status code
func (o *SecretsServiceGetListFieldBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field bad request response has a 4xx status code
func (o *SecretsServiceGetListFieldBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get list field bad request response has a 5xx status code
func (o *SecretsServiceGetListFieldBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field bad request response a status code equal to that given
func (o *SecretsServiceGetListFieldBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the secrets service get list field bad request response
func (o *SecretsServiceGetListFieldBadRequest) Code() int {
	return 400
}

func (o *SecretsServiceGetListFieldBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetListFieldBadRequest) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldBadRequest  %+v", 400, o.Payload)
}

func (o *SecretsServiceGetListFieldBadRequest) GetPayload() *models.BadRequestResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldForbidden creates a SecretsServiceGetListFieldForbidden with default headers values
func NewSecretsServiceGetListFieldForbidden() *SecretsServiceGetListFieldForbidden {
	return &SecretsServiceGetListFieldForbidden{}
}

/*
SecretsServiceGetListFieldForbidden describes a response with status code 403, with default header values.

Authentication failed
*/
type SecretsServiceGetListFieldForbidden struct {
	Payload *models.AuthenticationFailedResponse
}

// IsSuccess returns true when this secrets service get list field forbidden response has a 2xx status code
func (o *SecretsServiceGetListFieldForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field forbidden response has a 3xx status code
func (o *SecretsServiceGetListFieldForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field forbidden response has a 4xx status code
func (o *SecretsServiceGetListFieldForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this secrets service get list field forbidden response has a 5xx status code
func (o *SecretsServiceGetListFieldForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this secrets service get list field forbidden response a status code equal to that given
func (o *SecretsServiceGetListFieldForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the secrets service get list field forbidden response
func (o *SecretsServiceGetListFieldForbidden) Code() int {
	return 403
}

func (o *SecretsServiceGetListFieldForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetListFieldForbidden) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldForbidden  %+v", 403, o.Payload)
}

func (o *SecretsServiceGetListFieldForbidden) GetPayload() *models.AuthenticationFailedResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AuthenticationFailedResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSecretsServiceGetListFieldInternalServerError creates a SecretsServiceGetListFieldInternalServerError with default headers values
func NewSecretsServiceGetListFieldInternalServerError() *SecretsServiceGetListFieldInternalServerError {
	return &SecretsServiceGetListFieldInternalServerError{}
}

/*
SecretsServiceGetListFieldInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type SecretsServiceGetListFieldInternalServerError struct {
	Payload *models.InternalServerErrorResponse
}

// IsSuccess returns true when this secrets service get list field internal server error response has a 2xx status code
func (o *SecretsServiceGetListFieldInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this secrets service get list field internal server error response has a 3xx status code
func (o *SecretsServiceGetListFieldInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this secrets service get list field internal server error response has a 4xx status code
func (o *SecretsServiceGetListFieldInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this secrets service get list field internal server error response has a 5xx status code
func (o *SecretsServiceGetListFieldInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this secrets service get list field internal server error response a status code equal to that given
func (o *SecretsServiceGetListFieldInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the secrets service get list field internal server error response
func (o *SecretsServiceGetListFieldInternalServerError) Code() int {
	return 500
}

func (o *SecretsServiceGetListFieldInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetListFieldInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/v1/secrets/{id}/fields/{slug}/list][%d] secretsServiceGetListFieldInternalServerError  %+v", 500, o.Payload)
}

func (o *SecretsServiceGetListFieldInternalServerError) GetPayload() *models.InternalServerErrorResponse {
	return o.Payload
}

func (o *SecretsServiceGetListFieldInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InternalServerErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
