// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/secret-server/client-api/models"
)

// NewSecretsServiceUpdateExpirationParams creates a new SecretsServiceUpdateExpirationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecretsServiceUpdateExpirationParams() *SecretsServiceUpdateExpirationParams {
	return &SecretsServiceUpdateExpirationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsServiceUpdateExpirationParamsWithTimeout creates a new SecretsServiceUpdateExpirationParams object
// with the ability to set a timeout on a request.
func NewSecretsServiceUpdateExpirationParamsWithTimeout(timeout time.Duration) *SecretsServiceUpdateExpirationParams {
	return &SecretsServiceUpdateExpirationParams{
		timeout: timeout,
	}
}

// NewSecretsServiceUpdateExpirationParamsWithContext creates a new SecretsServiceUpdateExpirationParams object
// with the ability to set a context for a request.
func NewSecretsServiceUpdateExpirationParamsWithContext(ctx context.Context) *SecretsServiceUpdateExpirationParams {
	return &SecretsServiceUpdateExpirationParams{
		Context: ctx,
	}
}

// NewSecretsServiceUpdateExpirationParamsWithHTTPClient creates a new SecretsServiceUpdateExpirationParams object
// with the ability to set a custom HTTPClient for a request.
func NewSecretsServiceUpdateExpirationParamsWithHTTPClient(client *http.Client) *SecretsServiceUpdateExpirationParams {
	return &SecretsServiceUpdateExpirationParams{
		HTTPClient: client,
	}
}

/*
SecretsServiceUpdateExpirationParams contains all the parameters to send to the API endpoint

	for the secrets service update expiration operation.

	Typically these are written to a http.Request.
*/
type SecretsServiceUpdateExpirationParams struct {

	/* Args.

	   args
	*/
	Args *models.SecretDetailUpdateExpirationArgs

	/* AutoCheckIn.

	   Automatically check in a secret after finding or updating.
	*/
	AutoCheckIn *bool

	/* AutoCheckout.

	   Automatically check out secret before finding or updating.
	*/
	AutoCheckout *bool

	/* AutoComment.

	   Leave a comment when checking in or out.
	*/
	AutoComment *string

	/* ForceCheckIn.

	   If secret is checked out, then force a check in.
	*/
	ForceCheckIn *bool

	/* ID.

	   id

	   Format: int32
	*/
	ID int32

	/* SecretPath.

	   A full path including folder and secret name can be passed as a query string parameter when the secret ID is set to 0.  This will lookup the secret ID by path.
	*/
	SecretPath *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the secrets service update expiration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUpdateExpirationParams) WithDefaults() *SecretsServiceUpdateExpirationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the secrets service update expiration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUpdateExpirationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithTimeout(timeout time.Duration) *SecretsServiceUpdateExpirationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithContext(ctx context.Context) *SecretsServiceUpdateExpirationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithHTTPClient(client *http.Client) *SecretsServiceUpdateExpirationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithArgs(args *models.SecretDetailUpdateExpirationArgs) *SecretsServiceUpdateExpirationParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetArgs(args *models.SecretDetailUpdateExpirationArgs) {
	o.Args = args
}

// WithAutoCheckIn adds the autoCheckIn to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithAutoCheckIn(autoCheckIn *bool) *SecretsServiceUpdateExpirationParams {
	o.SetAutoCheckIn(autoCheckIn)
	return o
}

// SetAutoCheckIn adds the autoCheckIn to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetAutoCheckIn(autoCheckIn *bool) {
	o.AutoCheckIn = autoCheckIn
}

// WithAutoCheckout adds the autoCheckout to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithAutoCheckout(autoCheckout *bool) *SecretsServiceUpdateExpirationParams {
	o.SetAutoCheckout(autoCheckout)
	return o
}

// SetAutoCheckout adds the autoCheckout to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetAutoCheckout(autoCheckout *bool) {
	o.AutoCheckout = autoCheckout
}

// WithAutoComment adds the autoComment to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithAutoComment(autoComment *string) *SecretsServiceUpdateExpirationParams {
	o.SetAutoComment(autoComment)
	return o
}

// SetAutoComment adds the autoComment to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetAutoComment(autoComment *string) {
	o.AutoComment = autoComment
}

// WithForceCheckIn adds the forceCheckIn to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithForceCheckIn(forceCheckIn *bool) *SecretsServiceUpdateExpirationParams {
	o.SetForceCheckIn(forceCheckIn)
	return o
}

// SetForceCheckIn adds the forceCheckIn to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetForceCheckIn(forceCheckIn *bool) {
	o.ForceCheckIn = forceCheckIn
}

// WithID adds the id to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithID(id int32) *SecretsServiceUpdateExpirationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetID(id int32) {
	o.ID = id
}

// WithSecretPath adds the secretPath to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) WithSecretPath(secretPath *string) *SecretsServiceUpdateExpirationParams {
	o.SetSecretPath(secretPath)
	return o
}

// SetSecretPath adds the secretPath to the secrets service update expiration params
func (o *SecretsServiceUpdateExpirationParams) SetSecretPath(secretPath *string) {
	o.SecretPath = secretPath
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsServiceUpdateExpirationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	if o.AutoCheckIn != nil {

		// query param autoCheckIn
		var qrAutoCheckIn bool

		if o.AutoCheckIn != nil {
			qrAutoCheckIn = *o.AutoCheckIn
		}
		qAutoCheckIn := swag.FormatBool(qrAutoCheckIn)
		if qAutoCheckIn != "" {

			if err := r.SetQueryParam("autoCheckIn", qAutoCheckIn); err != nil {
				return err
			}
		}
	}

	if o.AutoCheckout != nil {

		// query param autoCheckout
		var qrAutoCheckout bool

		if o.AutoCheckout != nil {
			qrAutoCheckout = *o.AutoCheckout
		}
		qAutoCheckout := swag.FormatBool(qrAutoCheckout)
		if qAutoCheckout != "" {

			if err := r.SetQueryParam("autoCheckout", qAutoCheckout); err != nil {
				return err
			}
		}
	}

	if o.AutoComment != nil {

		// query param autoComment
		var qrAutoComment string

		if o.AutoComment != nil {
			qrAutoComment = *o.AutoComment
		}
		qAutoComment := qrAutoComment
		if qAutoComment != "" {

			if err := r.SetQueryParam("autoComment", qAutoComment); err != nil {
				return err
			}
		}
	}

	if o.ForceCheckIn != nil {

		// query param forceCheckIn
		var qrForceCheckIn bool

		if o.ForceCheckIn != nil {
			qrForceCheckIn = *o.ForceCheckIn
		}
		qForceCheckIn := swag.FormatBool(qrForceCheckIn)
		if qForceCheckIn != "" {

			if err := r.SetQueryParam("forceCheckIn", qForceCheckIn); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.SecretPath != nil {

		// query param secretPath
		var qrSecretPath string

		if o.SecretPath != nil {
			qrSecretPath = *o.SecretPath
		}
		qSecretPath := qrSecretPath
		if qSecretPath != "" {

			if err := r.SetQueryParam("secretPath", qSecretPath); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
