// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/secret-server/client-api/models"
)

// NewSecretsServiceUpdateListFieldListDefinitionsParams creates a new SecretsServiceUpdateListFieldListDefinitionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecretsServiceUpdateListFieldListDefinitionsParams() *SecretsServiceUpdateListFieldListDefinitionsParams {
	return &SecretsServiceUpdateListFieldListDefinitionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsServiceUpdateListFieldListDefinitionsParamsWithTimeout creates a new SecretsServiceUpdateListFieldListDefinitionsParams object
// with the ability to set a timeout on a request.
func NewSecretsServiceUpdateListFieldListDefinitionsParamsWithTimeout(timeout time.Duration) *SecretsServiceUpdateListFieldListDefinitionsParams {
	return &SecretsServiceUpdateListFieldListDefinitionsParams{
		timeout: timeout,
	}
}

// NewSecretsServiceUpdateListFieldListDefinitionsParamsWithContext creates a new SecretsServiceUpdateListFieldListDefinitionsParams object
// with the ability to set a context for a request.
func NewSecretsServiceUpdateListFieldListDefinitionsParamsWithContext(ctx context.Context) *SecretsServiceUpdateListFieldListDefinitionsParams {
	return &SecretsServiceUpdateListFieldListDefinitionsParams{
		Context: ctx,
	}
}

// NewSecretsServiceUpdateListFieldListDefinitionsParamsWithHTTPClient creates a new SecretsServiceUpdateListFieldListDefinitionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewSecretsServiceUpdateListFieldListDefinitionsParamsWithHTTPClient(client *http.Client) *SecretsServiceUpdateListFieldListDefinitionsParams {
	return &SecretsServiceUpdateListFieldListDefinitionsParams{
		HTTPClient: client,
	}
}

/*
SecretsServiceUpdateListFieldListDefinitionsParams contains all the parameters to send to the API endpoint

	for the secrets service update list field list definitions operation.

	Typically these are written to a http.Request.
*/
type SecretsServiceUpdateListFieldListDefinitionsParams struct {

	/* Args.

	   Secret options
	*/
	Args *models.SecretListFieldListArgs

	/* AutoCheckIn.

	   Automatically check in a secret after finding or updating.
	*/
	AutoCheckIn *bool

	/* AutoCheckout.

	   Automatically check out secret before finding or updating.
	*/
	AutoCheckout *bool

	/* AutoComment.

	   Leave a comment when checking in or out.
	*/
	AutoComment *string

	/* ForceCheckIn.

	   If secret is checked out, then force a check in.
	*/
	ForceCheckIn *bool

	/* ID.

	   Secret ID

	   Format: int32
	*/
	ID int32

	/* Slug.

	   Secret field name
	*/
	Slug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the secrets service update list field list definitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithDefaults() *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the secrets service update list field list definitions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithTimeout(timeout time.Duration) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithContext(ctx context.Context) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithHTTPClient(client *http.Client) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithArgs(args *models.SecretListFieldListArgs) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetArgs(args *models.SecretListFieldListArgs) {
	o.Args = args
}

// WithAutoCheckIn adds the autoCheckIn to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithAutoCheckIn(autoCheckIn *bool) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetAutoCheckIn(autoCheckIn)
	return o
}

// SetAutoCheckIn adds the autoCheckIn to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetAutoCheckIn(autoCheckIn *bool) {
	o.AutoCheckIn = autoCheckIn
}

// WithAutoCheckout adds the autoCheckout to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithAutoCheckout(autoCheckout *bool) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetAutoCheckout(autoCheckout)
	return o
}

// SetAutoCheckout adds the autoCheckout to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetAutoCheckout(autoCheckout *bool) {
	o.AutoCheckout = autoCheckout
}

// WithAutoComment adds the autoComment to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithAutoComment(autoComment *string) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetAutoComment(autoComment)
	return o
}

// SetAutoComment adds the autoComment to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetAutoComment(autoComment *string) {
	o.AutoComment = autoComment
}

// WithForceCheckIn adds the forceCheckIn to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithForceCheckIn(forceCheckIn *bool) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetForceCheckIn(forceCheckIn)
	return o
}

// SetForceCheckIn adds the forceCheckIn to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetForceCheckIn(forceCheckIn *bool) {
	o.ForceCheckIn = forceCheckIn
}

// WithID adds the id to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithID(id int32) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetID(id int32) {
	o.ID = id
}

// WithSlug adds the slug to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WithSlug(slug string) *SecretsServiceUpdateListFieldListDefinitionsParams {
	o.SetSlug(slug)
	return o
}

// SetSlug adds the slug to the secrets service update list field list definitions params
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) SetSlug(slug string) {
	o.Slug = slug
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsServiceUpdateListFieldListDefinitionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	if o.AutoCheckIn != nil {

		// query param autoCheckIn
		var qrAutoCheckIn bool

		if o.AutoCheckIn != nil {
			qrAutoCheckIn = *o.AutoCheckIn
		}
		qAutoCheckIn := swag.FormatBool(qrAutoCheckIn)
		if qAutoCheckIn != "" {

			if err := r.SetQueryParam("autoCheckIn", qAutoCheckIn); err != nil {
				return err
			}
		}
	}

	if o.AutoCheckout != nil {

		// query param autoCheckout
		var qrAutoCheckout bool

		if o.AutoCheckout != nil {
			qrAutoCheckout = *o.AutoCheckout
		}
		qAutoCheckout := swag.FormatBool(qrAutoCheckout)
		if qAutoCheckout != "" {

			if err := r.SetQueryParam("autoCheckout", qAutoCheckout); err != nil {
				return err
			}
		}
	}

	if o.AutoComment != nil {

		// query param autoComment
		var qrAutoComment string

		if o.AutoComment != nil {
			qrAutoComment = *o.AutoComment
		}
		qAutoComment := qrAutoComment
		if qAutoComment != "" {

			if err := r.SetQueryParam("autoComment", qAutoComment); err != nil {
				return err
			}
		}
	}

	if o.ForceCheckIn != nil {

		// query param forceCheckIn
		var qrForceCheckIn bool

		if o.ForceCheckIn != nil {
			qrForceCheckIn = *o.ForceCheckIn
		}
		qForceCheckIn := swag.FormatBool(qrForceCheckIn)
		if qForceCheckIn != "" {

			if err := r.SetQueryParam("forceCheckIn", qForceCheckIn); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	// path param slug
	if err := r.SetPathParam("slug", o.Slug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
