// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewSecretsServiceUndeleteSecretV2Params creates a new SecretsServiceUndeleteSecretV2Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSecretsServiceUndeleteSecretV2Params() *SecretsServiceUndeleteSecretV2Params {
	return &SecretsServiceUndeleteSecretV2Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewSecretsServiceUndeleteSecretV2ParamsWithTimeout creates a new SecretsServiceUndeleteSecretV2Params object
// with the ability to set a timeout on a request.
func NewSecretsServiceUndeleteSecretV2ParamsWithTimeout(timeout time.Duration) *SecretsServiceUndeleteSecretV2Params {
	return &SecretsServiceUndeleteSecretV2Params{
		timeout: timeout,
	}
}

// NewSecretsServiceUndeleteSecretV2ParamsWithContext creates a new SecretsServiceUndeleteSecretV2Params object
// with the ability to set a context for a request.
func NewSecretsServiceUndeleteSecretV2ParamsWithContext(ctx context.Context) *SecretsServiceUndeleteSecretV2Params {
	return &SecretsServiceUndeleteSecretV2Params{
		Context: ctx,
	}
}

// NewSecretsServiceUndeleteSecretV2ParamsWithHTTPClient creates a new SecretsServiceUndeleteSecretV2Params object
// with the ability to set a custom HTTPClient for a request.
func NewSecretsServiceUndeleteSecretV2ParamsWithHTTPClient(client *http.Client) *SecretsServiceUndeleteSecretV2Params {
	return &SecretsServiceUndeleteSecretV2Params{
		HTTPClient: client,
	}
}

/*
SecretsServiceUndeleteSecretV2Params contains all the parameters to send to the API endpoint

	for the secrets service undelete secret v2 operation.

	Typically these are written to a http.Request.
*/
type SecretsServiceUndeleteSecretV2Params struct {

	/* ID.

	   id

	   Format: int32
	*/
	ID int32

	/* SecretPath.

	   A full path including folder and secret name can be passed as a query string parameter when the secret ID is set to 0.  This will lookup the secret ID by path.
	*/
	SecretPath *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the secrets service undelete secret v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUndeleteSecretV2Params) WithDefaults() *SecretsServiceUndeleteSecretV2Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the secrets service undelete secret v2 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SecretsServiceUndeleteSecretV2Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) WithTimeout(timeout time.Duration) *SecretsServiceUndeleteSecretV2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) WithContext(ctx context.Context) *SecretsServiceUndeleteSecretV2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) WithHTTPClient(client *http.Client) *SecretsServiceUndeleteSecretV2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) WithID(id int32) *SecretsServiceUndeleteSecretV2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) SetID(id int32) {
	o.ID = id
}

// WithSecretPath adds the secretPath to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) WithSecretPath(secretPath *string) *SecretsServiceUndeleteSecretV2Params {
	o.SetSecretPath(secretPath)
	return o
}

// SetSecretPath adds the secretPath to the secrets service undelete secret v2 params
func (o *SecretsServiceUndeleteSecretV2Params) SetSecretPath(secretPath *string) {
	o.SecretPath = secretPath
}

// WriteToRequest writes these params to a swagger request
func (o *SecretsServiceUndeleteSecretV2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.SecretPath != nil {

		// query param secretPath
		var qrSecretPath string

		if o.SecretPath != nil {
			qrSecretPath = *o.SecretPath
		}
		qSecretPath := qrSecretPath
		if qSecretPath != "" {

			if err := r.SetQueryParam("secretPath", qSecretPath); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
