// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRolesServiceGetRoleGroupsParams creates a new RolesServiceGetRoleGroupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRolesServiceGetRoleGroupsParams() *RolesServiceGetRoleGroupsParams {
	return &RolesServiceGetRoleGroupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRolesServiceGetRoleGroupsParamsWithTimeout creates a new RolesServiceGetRoleGroupsParams object
// with the ability to set a timeout on a request.
func NewRolesServiceGetRoleGroupsParamsWithTimeout(timeout time.Duration) *RolesServiceGetRoleGroupsParams {
	return &RolesServiceGetRoleGroupsParams{
		timeout: timeout,
	}
}

// NewRolesServiceGetRoleGroupsParamsWithContext creates a new RolesServiceGetRoleGroupsParams object
// with the ability to set a context for a request.
func NewRolesServiceGetRoleGroupsParamsWithContext(ctx context.Context) *RolesServiceGetRoleGroupsParams {
	return &RolesServiceGetRoleGroupsParams{
		Context: ctx,
	}
}

// NewRolesServiceGetRoleGroupsParamsWithHTTPClient creates a new RolesServiceGetRoleGroupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRolesServiceGetRoleGroupsParamsWithHTTPClient(client *http.Client) *RolesServiceGetRoleGroupsParams {
	return &RolesServiceGetRoleGroupsParams{
		HTTPClient: client,
	}
}

/*
RolesServiceGetRoleGroupsParams contains all the parameters to send to the API endpoint

	for the roles service get role groups operation.

	Typically these are written to a http.Request.
*/
type RolesServiceGetRoleGroupsParams struct {

	/* FilterIncludeInactiveUsersForGroup.

	   Whether to include inactive users in the results
	*/
	FilterIncludeInactiveUsersForGroup *bool

	/* FilterUserDomainID.

	   Filter only users in a specific domain

	   Format: int32
	*/
	FilterUserDomainID *int32

	/* ID.

	   id

	   Format: int32
	*/
	ID int32

	/* Skip.

	   Number of records to skip before taking results

	   Format: int32
	*/
	Skip *int32

	/* SortBy0Direction.

	   Sort direction
	*/
	SortBy0Direction *string

	/* SortBy0Name.

	   Sort field name
	*/
	SortBy0Name *string

	/* SortBy0Priority.

	   Priority index. Sorts with lower values are executed earlier

	   Format: int32
	*/
	SortBy0Priority *int32

	/* Take.

	   Maximum number of records to include in results

	   Format: int32
	*/
	Take *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the roles service get role groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RolesServiceGetRoleGroupsParams) WithDefaults() *RolesServiceGetRoleGroupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the roles service get role groups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RolesServiceGetRoleGroupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithTimeout(timeout time.Duration) *RolesServiceGetRoleGroupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithContext(ctx context.Context) *RolesServiceGetRoleGroupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithHTTPClient(client *http.Client) *RolesServiceGetRoleGroupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterIncludeInactiveUsersForGroup adds the filterIncludeInactiveUsersForGroup to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithFilterIncludeInactiveUsersForGroup(filterIncludeInactiveUsersForGroup *bool) *RolesServiceGetRoleGroupsParams {
	o.SetFilterIncludeInactiveUsersForGroup(filterIncludeInactiveUsersForGroup)
	return o
}

// SetFilterIncludeInactiveUsersForGroup adds the filterIncludeInactiveUsersForGroup to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetFilterIncludeInactiveUsersForGroup(filterIncludeInactiveUsersForGroup *bool) {
	o.FilterIncludeInactiveUsersForGroup = filterIncludeInactiveUsersForGroup
}

// WithFilterUserDomainID adds the filterUserDomainID to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithFilterUserDomainID(filterUserDomainID *int32) *RolesServiceGetRoleGroupsParams {
	o.SetFilterUserDomainID(filterUserDomainID)
	return o
}

// SetFilterUserDomainID adds the filterUserDomainId to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetFilterUserDomainID(filterUserDomainID *int32) {
	o.FilterUserDomainID = filterUserDomainID
}

// WithID adds the id to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithID(id int32) *RolesServiceGetRoleGroupsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetID(id int32) {
	o.ID = id
}

// WithSkip adds the skip to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithSkip(skip *int32) *RolesServiceGetRoleGroupsParams {
	o.SetSkip(skip)
	return o
}

// SetSkip adds the skip to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetSkip(skip *int32) {
	o.Skip = skip
}

// WithSortBy0Direction adds the sortBy0Direction to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithSortBy0Direction(sortBy0Direction *string) *RolesServiceGetRoleGroupsParams {
	o.SetSortBy0Direction(sortBy0Direction)
	return o
}

// SetSortBy0Direction adds the sortBy0Direction to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetSortBy0Direction(sortBy0Direction *string) {
	o.SortBy0Direction = sortBy0Direction
}

// WithSortBy0Name adds the sortBy0Name to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithSortBy0Name(sortBy0Name *string) *RolesServiceGetRoleGroupsParams {
	o.SetSortBy0Name(sortBy0Name)
	return o
}

// SetSortBy0Name adds the sortBy0Name to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetSortBy0Name(sortBy0Name *string) {
	o.SortBy0Name = sortBy0Name
}

// WithSortBy0Priority adds the sortBy0Priority to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithSortBy0Priority(sortBy0Priority *int32) *RolesServiceGetRoleGroupsParams {
	o.SetSortBy0Priority(sortBy0Priority)
	return o
}

// SetSortBy0Priority adds the sortBy0Priority to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetSortBy0Priority(sortBy0Priority *int32) {
	o.SortBy0Priority = sortBy0Priority
}

// WithTake adds the take to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) WithTake(take *int32) *RolesServiceGetRoleGroupsParams {
	o.SetTake(take)
	return o
}

// SetTake adds the take to the roles service get role groups params
func (o *RolesServiceGetRoleGroupsParams) SetTake(take *int32) {
	o.Take = take
}

// WriteToRequest writes these params to a swagger request
func (o *RolesServiceGetRoleGroupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterIncludeInactiveUsersForGroup != nil {

		// query param filter.includeInactiveUsersForGroup
		var qrFilterIncludeInactiveUsersForGroup bool

		if o.FilterIncludeInactiveUsersForGroup != nil {
			qrFilterIncludeInactiveUsersForGroup = *o.FilterIncludeInactiveUsersForGroup
		}
		qFilterIncludeInactiveUsersForGroup := swag.FormatBool(qrFilterIncludeInactiveUsersForGroup)
		if qFilterIncludeInactiveUsersForGroup != "" {

			if err := r.SetQueryParam("filter.includeInactiveUsersForGroup", qFilterIncludeInactiveUsersForGroup); err != nil {
				return err
			}
		}
	}

	if o.FilterUserDomainID != nil {

		// query param filter.userDomainId
		var qrFilterUserDomainID int32

		if o.FilterUserDomainID != nil {
			qrFilterUserDomainID = *o.FilterUserDomainID
		}
		qFilterUserDomainID := swag.FormatInt32(qrFilterUserDomainID)
		if qFilterUserDomainID != "" {

			if err := r.SetQueryParam("filter.userDomainId", qFilterUserDomainID); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if o.Skip != nil {

		// query param skip
		var qrSkip int32

		if o.Skip != nil {
			qrSkip = *o.Skip
		}
		qSkip := swag.FormatInt32(qrSkip)
		if qSkip != "" {

			if err := r.SetQueryParam("skip", qSkip); err != nil {
				return err
			}
		}
	}

	if o.SortBy0Direction != nil {

		// query param sortBy[0].direction
		var qrSortBy0Direction string

		if o.SortBy0Direction != nil {
			qrSortBy0Direction = *o.SortBy0Direction
		}
		qSortBy0Direction := qrSortBy0Direction
		if qSortBy0Direction != "" {

			if err := r.SetQueryParam("sortBy[0].direction", qSortBy0Direction); err != nil {
				return err
			}
		}
	}

	if o.SortBy0Name != nil {

		// query param sortBy[0].name
		var qrSortBy0Name string

		if o.SortBy0Name != nil {
			qrSortBy0Name = *o.SortBy0Name
		}
		qSortBy0Name := qrSortBy0Name
		if qSortBy0Name != "" {

			if err := r.SetQueryParam("sortBy[0].name", qSortBy0Name); err != nil {
				return err
			}
		}
	}

	if o.SortBy0Priority != nil {

		// query param sortBy[0].priority
		var qrSortBy0Priority int32

		if o.SortBy0Priority != nil {
			qrSortBy0Priority = *o.SortBy0Priority
		}
		qSortBy0Priority := swag.FormatInt32(qrSortBy0Priority)
		if qSortBy0Priority != "" {

			if err := r.SetQueryParam("sortBy[0].priority", qSortBy0Priority); err != nil {
				return err
			}
		}
	}

	if o.Take != nil {

		// query param take
		var qrTake int32

		if o.Take != nil {
			qrTake = *o.Take
		}
		qTake := swag.FormatInt32(qrTake)
		if qTake != "" {

			if err := r.SetQueryParam("take", qTake); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
