// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/secret-server/client-api/models"
)

// NewUsersServiceCreateUserRolesParams creates a new UsersServiceCreateUserRolesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUsersServiceCreateUserRolesParams() *UsersServiceCreateUserRolesParams {
	return &UsersServiceCreateUserRolesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUsersServiceCreateUserRolesParamsWithTimeout creates a new UsersServiceCreateUserRolesParams object
// with the ability to set a timeout on a request.
func NewUsersServiceCreateUserRolesParamsWithTimeout(timeout time.Duration) *UsersServiceCreateUserRolesParams {
	return &UsersServiceCreateUserRolesParams{
		timeout: timeout,
	}
}

// NewUsersServiceCreateUserRolesParamsWithContext creates a new UsersServiceCreateUserRolesParams object
// with the ability to set a context for a request.
func NewUsersServiceCreateUserRolesParamsWithContext(ctx context.Context) *UsersServiceCreateUserRolesParams {
	return &UsersServiceCreateUserRolesParams{
		Context: ctx,
	}
}

// NewUsersServiceCreateUserRolesParamsWithHTTPClient creates a new UsersServiceCreateUserRolesParams object
// with the ability to set a custom HTTPClient for a request.
func NewUsersServiceCreateUserRolesParamsWithHTTPClient(client *http.Client) *UsersServiceCreateUserRolesParams {
	return &UsersServiceCreateUserRolesParams{
		HTTPClient: client,
	}
}

/*
UsersServiceCreateUserRolesParams contains all the parameters to send to the API endpoint

	for the users service create user roles operation.

	Typically these are written to a http.Request.
*/
type UsersServiceCreateUserRolesParams struct {

	/* Args.

	   args
	*/
	Args *models.RoleAssignments

	/* ID.

	   id

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the users service create user roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersServiceCreateUserRolesParams) WithDefaults() *UsersServiceCreateUserRolesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the users service create user roles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UsersServiceCreateUserRolesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) WithTimeout(timeout time.Duration) *UsersServiceCreateUserRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) WithContext(ctx context.Context) *UsersServiceCreateUserRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) WithHTTPClient(client *http.Client) *UsersServiceCreateUserRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithArgs adds the args to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) WithArgs(args *models.RoleAssignments) *UsersServiceCreateUserRolesParams {
	o.SetArgs(args)
	return o
}

// SetArgs adds the args to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) SetArgs(args *models.RoleAssignments) {
	o.Args = args
}

// WithID adds the id to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) WithID(id int32) *UsersServiceCreateUserRolesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the users service create user roles params
func (o *UsersServiceCreateUserRolesParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UsersServiceCreateUserRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Args != nil {
		if err := r.SetBodyParam(o.Args); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
